/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_omegaup_transact_Message */

#ifndef _Included_com_omegaup_transact_Message
#define _Included_com_omegaup_transact_Message
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_omegaup_transact_Message
 * Method:    allocate
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_omegaup_transact_Message_allocate
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_omegaup_transact_Message
 * Method:    receive
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_omegaup_transact_Message_receive
  (JNIEnv *, jobject);

/*
 * Class:     com_omegaup_transact_Message
 * Method:    send
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_omegaup_transact_Message_send
  (JNIEnv *, jobject);

/*
 * Class:     com_omegaup_transact_Message
 * Method:    writeByte
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_omegaup_transact_Message_writeByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_omegaup_transact_Message
 * Method:    writeShort
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_omegaup_transact_Message_writeShort
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_omegaup_transact_Message
 * Method:    writeInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_omegaup_transact_Message_writeInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_omegaup_transact_Message
 * Method:    writeLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_omegaup_transact_Message_writeLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omegaup_transact_Message
 * Method:    readByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_omegaup_transact_Message_readByte
  (JNIEnv *, jobject);

/*
 * Class:     com_omegaup_transact_Message
 * Method:    readShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_omegaup_transact_Message_readShort
  (JNIEnv *, jobject);

/*
 * Class:     com_omegaup_transact_Message
 * Method:    readInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_omegaup_transact_Message_readInt
  (JNIEnv *, jobject);

/*
 * Class:     com_omegaup_transact_Message
 * Method:    readLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_omegaup_transact_Message_readLong
  (JNIEnv *, jobject);

/*
 * Class:     com_omegaup_transact_Message
 * Method:    nativeInit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_omegaup_transact_Message_nativeInit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omegaup_transact_Message
 * Method:    nativeFinalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_omegaup_transact_Message_nativeFinalize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
