/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_omegaup_transact_Interface */

#ifndef _Included_com_omegaup_transact_Interface
#define _Included_com_omegaup_transact_Interface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_omegaup_transact_Interface
 * Method:    nativeInit
 * Signature: (ZLjava/lang/String;Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_omegaup_transact_Interface_nativeInit
  (JNIEnv *, jobject, jboolean, jstring, jstring, jlong);

/*
 * Class:     com_omegaup_transact_Interface
 * Method:    nativeFinalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_omegaup_transact_Interface_nativeFinalize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
